name: sorting-words-and-numbers
version: 0.1.0.0
github: "githubuser/sorting-words-and-numbers"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/sorting-words-and-numbers#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sorting-words-and-numbers-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sorting-words-and-numbers

tests:
  sorting-words-and-numbers-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sorting-words-and-numbers
